
import React, { useState } from 'react';
import MainLayout from '@/components/layout/MainLayout';
import StrategyCard from '@/components/yield/StrategyCard';
import { useYield } from '@/context/YieldContext';
import { useWallet } from '@/context/WalletContext';
import { Button } from '@/components/ui/button';
import LoadingAI from '@/components/ui/LoadingAI';
import { Bot, Database, Code, TrendingUp, Activity } from 'lucide-react';
import { toast } from '@/components/ui/sonner';
import { FeatureCard } from '@/components/ui/FeatureCard';

const Strategies = () => {
  const { userPositions, optimizeYield, executeStrategy } = useYield();
  const { isConnected } = useWallet();
  const [generatingStrategy, setGeneratingStrategy] = useState(false);
  const [strategyGenerated, setStrategyGenerated] = useState(false);

  // Current average APY across all positions
  const currentAverageApy = userPositions.length > 0
    ? userPositions.reduce((sum, pos) => sum + pos.apy, 0) / userPositions.length
    : 0;

  const handleGenerateStrategy = async () => {
    setGeneratingStrategy(true);
    try {
      await optimizeYield();
      setStrategyGenerated(true);
    } catch (error) {
      console.error("Failed to generate strategy:", error);
      toast.error("Failed to generate strategy");
    } finally {
      setGeneratingStrategy(false);
    }
  };

  const handleExecuteStrategy = async (strategyName: string) => {
    try {
      await executeStrategy(strategyName);
      toast.success("Strategy execution initiated!");
    } catch (error) {
      console.error("Failed to execute strategy:", error);
      toast.error("Failed to execute strategy");
    }
  };

  // Example strategies - in a real application these would be generated by the AI
  const strategies = [
    {
      title: "Balanced Yield Optimizer",
      description: "This strategy rebalances your portfolio to achieve higher yields while maintaining a low risk profile by allocating funds across established Base protocols.",
      currentApy: currentAverageApy,
      targetApy: currentAverageApy + 2.3,
      riskLevel: 'low' as const,
      action: "balanced"
    },
    {
      title: "Aggressive Growth Strategy",
      description: "Maximize your yield potential by redistributing assets to higher APY pools with a moderate risk tolerance, focusing on newer protocols with higher returns.",
      currentApy: currentAverageApy,
      targetApy: currentAverageApy + 5.8,
      riskLevel: 'moderate' as const,
      action: "aggressive"
    },
    {
      title: "Innovative Yield Farming",
      description: "Explore emerging opportunities in newly launched Base protocols with exceptional yield potential, while assuming higher risk for potentially superior returns.",
      currentApy: currentAverageApy,
      targetApy: currentAverageApy + 12.5,
      riskLevel: 'high' as const,
      action: "innovative"
    }
  ];

  const features = [
    {
      icon: <Database size={20} />,
      title: "Real-time DeFi Analysis",
      description: "Continuous analysis of Base DeFi pools using CDP SDK for onchain data, ensuring you always have the latest market intelligence.",
      highlight: true
    },
    {
      icon: <Code size={20} />,
      title: "Automated Smart Contracts",
      description: "Automated interactions to stake, unstake, or swap tokens across various Base protocols with optimal timing.",
      highlight: true
    },
    {
      icon: <Activity size={20} />,
      title: "Market Monitoring",
      description: "Constant monitoring of market conditions to identify the best yield opportunities as they emerge in real-time."
    },
    {
      icon: <TrendingUp size={20} />,
      title: "Capital Rebalancing",
      description: "Autonomous rebalancing of your portfolio to maximize returns while respecting your risk preferences."
    },
  ];

  return (
    <MainLayout>
      <div className="container mx-auto py-8">
        <div className="mb-8">
          <h1 className="text-3xl font-bold mb-2">AI Yield Strategies</h1>
          <p className="text-slate-600">
            Let our AI agent analyze your portfolio and generate optimized yield strategies to maximize your returns.
          </p>
        </div>

        {!isConnected ? (
          <div className="bg-slate-50 border border-slate-200 rounded-lg p-8 text-center">
            <Bot size={48} className="mx-auto mb-4 text-blue-500" />
            <h2 className="text-xl font-semibold mb-2">Connect Your Wallet</h2>
            <p className="text-slate-600 mb-4">
              Please connect your wallet to generate personalized yield strategies.
            </p>
          </div>
        ) : generatingStrategy ? (
          <div className="py-12">
            <LoadingAI text="AI Optimizing Your Yield Strategy" />
          </div>
        ) : !strategyGenerated ? (
          <>
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-8 mb-10">
              <div className="flex flex-col md:flex-row items-center gap-6">
                <div className="w-16 h-16 bg-gradient-to-tr from-blue-600 to-blue-400 rounded-full flex items-center justify-center">
                  <Bot size={32} className="text-white" />
                </div>
                <div className="flex-1 text-center md:text-left">
                  <h2 className="text-xl font-semibold mb-2">Generate Yield Strategy</h2>
                  <p className="text-slate-600 mb-6">
                    Our AI agent will analyze your portfolio and current market conditions to recommend optimal yield strategies.
                  </p>
                  <Button 
                    onClick={handleGenerateStrategy} 
                    size="lg"
                    className="bg-blue-600 hover:bg-blue-700"
                  >
                    Generate Strategy
                  </Button>
                </div>
              </div>
            </div>
            
            <div className="mb-10">
              <h2 className="text-xl font-semibold mb-6">Key Features</h2>
              <div className="grid md:grid-cols-2 gap-6">
                {features.map((feature, index) => (
                  <FeatureCard
                    key={index}
                    icon={feature.icon}
                    title={feature.title}
                    description={feature.description}
                    highlight={feature.highlight}
                    className={feature.highlight ? "border-blue-300" : ""}
                  />
                ))}
              </div>
            </div>
            
            <div className="bg-slate-50 border border-slate-200 rounded-lg p-6">
              <h3 className="text-lg font-medium mb-3">How It Works</h3>
              <p className="text-slate-600 mb-4">
                Our DeFi Yield Optimizer Agent processes multiple data streams to make informed investment decisions:
              </p>
              <ol className="list-decimal list-inside space-y-2 text-slate-600">
                <li>
                  <span className="font-medium">Protocol Analysis:</span> The agent scans Base DeFi protocols to identify
                  yield-generating opportunities, analyzing TVL, APY rates, and protocol risk scores.
                </li>
                <li>
                  <span className="font-medium">Strategy Generation:</span> Based on your risk preferences and market conditions,
                  the agent generates optimal strategies for your stablecoin assets.
                </li>
                <li>
                  <span className="font-medium">Smart Contract Execution:</span> When you approve a strategy, the agent
                  interacts with DeFi smart contracts to deploy your capital efficiently.
                </li>
                <li>
                  <span className="font-medium">Portfolio Monitoring:</span> The agent continuously monitors your positions
                  and market conditions, suggesting rebalances when better opportunities arise.
                </li>
              </ol>
            </div>
          </>
        ) : (
          <div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-8">
              {strategies.map((strategy) => (
                <StrategyCard
                  key={strategy.title}
                  title={strategy.title}
                  description={strategy.description}
                  currentApy={strategy.currentApy}
                  targetApy={strategy.targetApy}
                  riskLevel={strategy.riskLevel}
                  onExecute={() => handleExecuteStrategy(strategy.action)}
                />
              ))}
            </div>
            
            <div className="bg-slate-50 border border-slate-200 rounded-lg p-6 mt-6">
              <h3 className="text-lg font-medium mb-2">How It Works</h3>
              <p className="text-slate-600 text-sm">
                Our AI agent analyzes on-chain data across multiple DeFi protocols on Base to identify the most efficient yield strategies for your stablecoin assets. When you execute a strategy, the agent will automatically rebalance your portfolio by interacting with the relevant smart contracts to optimize your returns.
              </p>
            </div>
          </div>
        )}
      </div>
    </MainLayout>
  );
};

export default Strategies;
